### ISSUE TITLE
readme.md API

### ISSUE THREAD

**Issue by Mokerstier** [ofahchouch-gh/web-app-from-scratch-2021#10]
Je schrijft veel over de API en dat je een ip-ban kan krijgen maar ik kan zo 1, 2, 3 niet terugvinden wat ik moet doen om een ban te krijgen.

Hoeveel requests mag ik doen per uur? per dag? dit wil ik graag terug zien in de readme

**Comment by ofahchouch-gh** [comment]
Yes, gedaan. Bedankt voor de oplettendheid :)!
