### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by Mokerstier** [ofahchouch-gh/web-app-from-scratch-2021#11]
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/057a554f0dec88f283fc20329997fef88357bed1/src/modules/coin/CoinDetailController.js#L62-L66

Kan dit weg?

Houd je git schoon push geen code die je niet gebruikt of ga je dit later nog gebruiken?

**Comment by ofahchouch-gh** [comment]
Ja ik wou dit later gebruiken. Ik was vooral aan het knutselen, had het eigenlijk niet moeten pushen. 

Bedankt in iedere geval voor de oplettendheid :D!
