### ISSUE TITLE
Readme.md Actor diagram

### ISSUE THREAD

**Issue by Mokerstier** [ofahchouch-gh/web-app-from-scratch-2021#12]
Houd je actor diagram beknopt ik hoef hierin niet te zien welke values je allemaal aan de functies mee geeft.

Soms is less more ;)

**Comment by ofahchouch-gh** [comment]
Yes, zal daar volgende keer op gaan letten. Hier was ik eigenlijk een klassen diagram aan het tekenen. 

Hier en daar moet ik tevens het een en ander nog veranderen. Het is een voorlopige actor diagram.
