### ISSUE TITLE
Reduce function names

### ISSUE THREAD

**Issue by Mokerstier** [ofahchouch-gh/web-app-from-scratch-2021#13]
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/057a554f0dec88f283fc20329997fef88357bed1/src/modules/shared/models/candlestick/CandlestickModel.js#L20

Deze functie voert in principe een check uit dus volstaat de naam `check` ook voor mij, als er dan uitkomt bullish of bearish is voor de functie naam niet zo belangrijk.

**Comment by ofahchouch-gh** [comment]
Yes, bedankt voor de feedback. Ik zal proberen om niet te lange functie namen meer te gebruiken.
