### ISSUE TITLE
Peer review week 3

### ISSUE THREAD

**Issue by StanBankras** [ofahchouch-gh/web-app-from-scratch-2021#14]
## Structure & code quality
* Very advanced structure, which for me is a bit too advanced to understand at this point. For a small project like this, I assume it's not necessary, but I can tell you have thought this through very well!
* I think you probably looked at this, but you hardcoded some cryptos in here:
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/modules/cryptocurrency/CurrencyOverviewController.js#L9-L18
If you could get these through the API, it would improve it, since it will be more dynamic.
* Why do you use an async function here, if there's nothing that awaits?
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/app.js#L3-L6
* I would always avoid inline CSS, I recommend using a class instead
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/modules/coin/CoinDetailView.js#L158-L164
* You could make your sleep() function into a util, since you use it in different files
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/modules/coin/CoinDetailView.js#L193-L195
* I see some inconsistencies in the alignment / spacing:
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/modules/coin/CoinDetailView.js#L145-L148

## Data fetching, manipulation & visualization
* You could make your fetch function a util so it will be less code:
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/modules/binance/BinanceApiHandler.js#L36-L39
* You don't have to use a template literal if you only enter 1 variable without text:
```js
const fetchedRecentTradesListApiResponse = await fetch(`${url}`, { method: 'GET' });
```
* Here you don't use .find() correctly. Find is used to actually find an object or variable in an array, but you utilize it as a forEach. I would change it to a forEach instead.
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/modules/cryptocurrency/CurrencyOverviewController.js#L161-L170
* In your catch, you can use console.error instead of console.log (not necessary, but will make it more obvious):
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/modules/binance/BinanceApiHandler.js#L72-L74

## Handling states & routes
* I would personally use an ID or class per section, as this can be prone to errors if you start adding more section or elements. Also I would recommend adding and removing a class, instead of adding CSS with javascript directly:
https://github.com/ofahchouch-gh/web-app-from-scratch-2021/blob/9d83d5bcb3bbcf5296d8eff8661f355ce3e20a16/src/router/router.js#L4-L7
* Router looks clean other than my first remark
* You handle your templating through the different views, which is a nice way to do it in my opinion.

**Comment by ofahchouch-gh** [comment]
Thanks voor de feedback! Heb zo veel mogelijk feedback verwerkt in het project :)!
