### ISSUE TITLE
Feedback: Code (HTML)

### ISSUE THREAD

**Issue by StanBankras** [ofahchouch-gh/web-app-from-scratch-2021#2]
## HTML code feedback

* In your HTML, it is recommended to place your script tag near the bottom as it's better for the load time of the page. Right now it's in the **HEAD** section
```html
<head>
    ....
    <script type="module" defer src="./app.js"></script>
</head>

to:

<body>
    ....
    <script type="module" defer src="./app.js"></script>
</body>

or 

<body>
    ....
</body>
<script type="module" defer src="./app.js"></script>
```

* You have used a header element, which is good, but you don't have a <main>. For semantics, I would rewrite your middle section as:
```html
<main>
  <section>
    <aside></aside>
  </section>
</main>
```

**Comment by ofahchouch-gh** [comment]
Thanks, als een back-ender heb ik veel aan deze feedback :)!
