### ISSUE TITLE
Feedback: Code (JS)

### ISSUE THREAD

**Issue by StanBankras** [ofahchouch-gh/web-app-from-scratch-2021#3]
## Javascript feedback

* Generally, I think your function and variable names are quite long. They are very descriptive, but I think at some point too much description makes it less readable too.

* I was wondering why this has to be a function instead of just leaving this globally scoped as a `const`:
```js
function getListOfMostPopularCryptoCurrencies() {
    const listOfMostPopularCryptoTickerNames = [
        'BTCUSDT',
        'ETHUSDT',
         ......
    ];

    return listOfMostPopularCryptoTickerNames;
}
```

* You already got a lot of functionality in in this short time, which is great. My remark about efficiency, although maybe not noticable for a user: if I read it right, you re-render the whole table on each update. It might be an idea to look into making this more efficient and only edit innerText / innerHTML of things that need to be updated.

* Use of modules is nice, makes the code better maintainable and easier to read.

* For the Binance API handler, there is an Async function where you could also use Try/Catch instead of handling errors with promise handling:
```js
export async function fetchBidAndAskPriceOfSpecificTicker(tickerName) {
    let url = `${BINANCE_API_URL_PREFIX}/depth?symbol=${tickerName}&limit=5`;
    let fetchedTicker = null;

    await fetch(`${url}`, {
        method: 'GET'
    }).then(fetchedData => {
        return fetchedData.json();
    }).then(fetchedData => {
        fetchedTicker = fetchedData;
    }).catch(error => {
        // later afhandelen met een exception message
        console.log('failed to fetch data: ', error);
    });
    
    return fetchedTicker;
}

// could be

export async function fetchBidAndAskPriceOfSpecificTicker(tickerName) {
    try {
      let url = `${BINANCE_API_URL_PREFIX}/depth?symbol=${tickerName}&limit=5`;
      let fetchedTicker = null;
  
      const response = await fetch(`${url}`, { method: 'GET' };
      const data = await response.json();
      fetchedTicker = data;
      return fetchedTicker;
    } catch(error) {
        console.log('failed to fetch data: ', error);
    }
}

```

**Comment by ofahchouch-gh** [comment]
Thanks about the advice for using const instead of a getter. 

Yes the table is being re-rendered, but it shouldn't be that case. I had no time to refactor that. Will be doing that in the future.

The feedback about the try/catch is very useful!
