### ISSUE TITLE
Feedback: link to webpage?

### ISSUE THREAD

**Issue by Mokerstier** [ofahchouch-gh/web-app-from-scratch-2021#5]
Update je link naar je webpage nog even, het is dat je hem in discord had gezet anders kon ik hem niet bekijken.

Je bent lekker bezig wil je alleen 1 specifiek advies geven:
Probeer logische maar minder lange functie/variabelen namen te bedenken.

Soms kan je door woorden af tekorten al een heel eind komen.

PS ik zag dat Stan je deze feedback ook al had gegeven ;)

**Comment by ofahchouch-gh** [comment]
Thanks voor de feedback Wouter :)! Yes, zal daar rekening mee gaan houden.
