### ISSUE TITLE
Peer review week 1

### ISSUE THREAD

**Issue by RowinRuizendaal** [ofahchouch-gh/web-app-from-scratch-2021#6]
##### Is there a repo description at the top?

Yes there is a repo description

##### Is the repo open to issues?

Yes, as I am making an issue right now :)

##### Does it include a gitignore

Yes it does include a gitignore file

##### Is the concept described well in the readme?

Yes, the concept is described in the readme, all though maybe you can expand your description with what you will be making and why.

##### Is the API described in the readme?

The link t the Biance spot API redirects to your GitHub repo, maybe you can fix this by using the correct URL, so we can see what kind of API you're using :D

##### Try to understand the code flow

Nice to see that you are working with modules! this gives a better overview, really nice to have this already like this. Something I couldn't do due to the time :).

btw one of your files is called cryptocurrenyOverviewController.js.js I think you mean .js instead of js.js ? :)

The script tag is placed inside the head element, maybe its better to place it at the bottom of the body
 
##### Check the code against our course's best practices

(see above @Try to understand the code flow)

##### Check the code for consistency, is code being written the same way in different places?

Yes the code is consistent and is written the same way in different files

##### Does the code follow naming conventions? Do variable and function names make sense to you?

The long function names don't really bother me, as it is personally how you name certain functions although sometimes it can be hard to read, so maybe you should consider it to make it shorter.

**Comment by ofahchouch-gh** [comment]
Thanks for the feedback :)! I have done something with all the feedback.
