### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by InjuMichorius** [ofahchouch-gh/web-app-from-scratch-2021#7]
Hi Oussama 👋
I've reviewed your repo and found the following.
- Small spelling mistake; I ~~choose~~ this idea should be I chose this idea
- It would be nice if the README has a image at the top when you're done (so people know what to expect).
- The diagrams are very low quality in the README file, but when you click on them they seem fine
- Interaction diagram: make sure to use the [the right symbols!](https://www.gliffy.com/blog/guide-to-flowchart-symbols)
- Very chill and easy style, which is important when working with Crypto. The last column is a bit off with the alignment.
- Consider using a standard HTML format extension so your HTML will be neatly nested.
- Stay consistent with your code; in the HTML, you have one script-tag in the head and one in the body
- You're giving your functions very long names, maybe consider using comments explaining your code instead of the function itself.
- "Hier komt later nog een model voor de crypto coin" very small, but this is in Dutch ;)

Code looks very clean, nice use of models and easy to read map structure. The loading animation is a nice way to give the user feedback (it could show at how much %, but that's maybe a bit over the top). When downloading the project, it doesn't work and gives this error, but you already explained to me this is because you're using Linux. It might be a good idea to either fix it or mention this in your README.
`GET file:///C:Users/name/OneDrive/Bureaublad/Oussama/src/app.js
net::ERR_FAILED`

Is there a link to the live demo at the top? ✔️
Is the concept described well in the readme? ✔️
Is the API described in the readme? ✔️
Are the Actor and Interaction diagrams included? ✔️
Do the actors make sense to you? ✔️
Do you see any function you wouldn't expect for a certain Actor? ❌
Using the interaction diagram, figure out how the app functions ❌
Does the flow make sense to you? ✔️

**Comment by ofahchouch-gh** [comment]
Yes, zal de readme updaten. Ik heb wat extra tijd gestopt in de diagrammen, mijn interaction diagram is een activity diagram (UML). Vandaar dat dit er anders uit ziet, geen idee of dit wordt gewaardeerd door de beoordelaars.
