### ISSUE TITLE
Repository peer feedback week 2

### ISSUE THREAD

**Issue by HappyPantss** [ofahchouch-gh/web-app-from-scratch-2021#8]
Repository
Hey Oussama, bij deze mijn peer review op jouw repository voor de WAFS API opdracht, week 2.

Zie de vinkjes (✔️) en kruisjes (❌) niet als fout of goed, maar een vinkje is voor als je heta af hebt, en een kruisje voor als er nog iets mist :).

✔️ Is there a link to the live demo at the top?
Jazeker! Alleen nog een tip voor je 'description': ik zou hier nog even in het kort uitleggen wat/ waar voor het project is. En misschien wat tags toevoegen is altijd leuk :).

✔️ Is the concept described well in the readme?
Ja goede beschrijving! Misschien kan je nog neerzetten waarom je de top 20 laat zien, en wat mensen er aan hebben.

✔️ Is the API described in the readme?
Ja! Goede beschrijven wat de API is etc,

✔️ Are the Actor and Interaction diagrams included?
Ja!

Keep coding~~

**Comment by ofahchouch-gh** [comment]
Thanks :).
