### ISSUE TITLE
Code peer feedback week 2

### ISSUE THREAD

**Issue by HappyPantss** [ofahchouch-gh/web-app-from-scratch-2021#9]
Code
Hey Oussama, bij deze mijn peer review op jouw code voor de WAFS API opdracht, week 2.

Zie de vinkjes (✔️) en kruisjes (❌) niet als fout of goed, maar een vinkje is voor als je heta af hebt, en een kruisje voor als er nog iets mist :).

## Using the Actor diagram, figure out the structure of the code
✔️ Do the actors make sense to you?
Je hebt erg duidelijke en goede actors opgeschreven! 

✔️ Do you see any function you wouldn't expect for a certain Actor?
Ik zie geen rare functies!

## Using the interaction diagram, figure out how the app functions
✔️ Does the flow make sense to you?
De flow maakt erg veel sense aangezien je met vakjes werkt en met pijlen. Je kan zien waar er iets gebeurd als iets goed of fout gaat, alleen zou ik er nog wat tekst bij zetten, but that's me.

## Click through the live demo
✔️❌ Does it work the way you would expect it to? / What features or improvements would you like to see?
- Ten eerste: mooie loading state!
- De belangrijkste dingen zie ik staan, wat ik heel fijn vind.
- Je kan op de soort crypto drukken, en hier informatie over vinden denk ik? Dit werkt nog niet, maar dat wist je denk ik al.
- Ook HEEL fijn dat je terug kan zodra op een bepaalde crypto hebt gedrukt :)

Tips:
-  Bij mij lijnen de 2 laatste tabellen niet goed uit.
![Foutje](https://i.imgur.com/1PbqYFH.png)

## Browse the code
✔️Has it already been structured according to the diagrams?
Ja je structure ziet er goed uit, met modules apart en je router etc.

✔️ Think of structural improvements
Goed gedaan! Hier weet ik geen feedback voor.

✔️Check the code against our best practices
Je gebruikt insertAdjacentment, wat goed is, maar bedenk goed of dit de goede oplossing is voor jezelf! Je hebt bijvoorbeeld ook innerHTML, kijk wat voor jou de beste oplossing is.

✔️Check the code for consistency, is code being written the same way in different places?
Jep it does! Goed op gelet.

✔️ Does the code follow naming conventions? Do variable and function names make sense to you?
Je lange namen leggen gewoon goed uit wat wat doet, dus dit vind ik prima!

Keep coding~~

**Comment by ofahchouch-gh** [comment]
Thanks voor de feedback. De tabel heb ik helaas verkeerd gerendered, dit zal ik moeten aanpassen.
